
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-08
owner: ucsb-cs156-s26
repo_name: team02-s26-08
pull_requests: [{"author":{"id":"U_kgDODgRftg","is_bot":false,"login":"CMWENDY","name":"Wendy Contreras"},"headRefName":"wc-UCSBDiningCommonsMenuItem-placeholders","number":72,"title":"Add UCSBDiningCommonsMenuItem placeholder pages","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/72"},{"author":{"id":"U_kgDODgRftg","is_bot":false,"login":"CMWENDY","name":"Wendy Contreras"},"headRefName":"wc-UCSBDiningCommonsMenuItem-table","number":71,"title":"Add UCSBDiningCommonsMenuItem table component","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/71"},{"author":{"id":"U_kgDODgRftg","is_bot":false,"login":"CMWENDY","name":"Wendy Contreras"},"headRefName":"wc-UCSBDiningCommonsMenuItem-form","number":70,"title":"Added the form component for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/70"},{"author":{"id":"U_kgDOCVHSBA","is_bot":false,"login":"dev-anj","name":"Anjali Dev"},"headRefName":"menuitemreview-backend","number":69,"title":"copy backend CRUD operations for MenuItemReview","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/69"},{"author":{"id":"U_kgDOCWXSsA","is_bot":false,"login":"ccabacungan","name":""},"headRefName":"codex/cc-HelpRequest-backend","number":68,"title":"Add HelpRequest backend CRUD API","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/68"},{"author":{"id":"U_kgDOCVHlaQ","is_bot":false,"login":"riasingh455","name":""},"headRefName":"rs-recommendation-fixtures","number":64,"title":"redo the fixtures branch","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/64"},{"author":{"id":"U_kgDOCVPcVQ","is_bot":false,"login":"matthewli10","name":""},"headRefName":"matthewli-copy-files","number":62,"title":"ML - copy UCSBOrganization files from team01","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/62"}]
