
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-08
owner: ucsb-cs156-s26
repo_name: team02-s26-08
pull_requests: [{"author":{"id":"U_kgDOB-HICA","is_bot":false,"login":"taedonreth","name":"Taedon Reth"},"headRefName":"tr-articles-e2e-tests","number":122,"title":"Add Articles end-to-end test","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/122"},{"author":{"id":"U_kgDOB-HICA","is_bot":false,"login":"taedonreth","name":"Taedon Reth"},"headRefName":"tr-team03","number":121,"title":"Add integration test for Articles","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/121"},{"author":{"id":"U_kgDOCVPcVQ","is_bot":false,"login":"matthewli10","name":""},"headRefName":"matthewli-organization-integration-test","number":118,"title":"Add UCSBOrganization integration test","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/118"},{"author":{"id":"U_kgDOCVPcVQ","is_bot":false,"login":"matthewli10","name":""},"headRefName":"matthewli-organization-e2e-test","number":117,"title":"Add UCSBOrganization end-to-end test","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/117"}]
