
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-08
owner: ucsb-cs156-s26
repo_name: team02-s26-08
pull_requests: [{"author":{"id":"U_kgDOCWXSsA","is_bot":false,"login":"ccabacungan","name":""},"headRefName":"codex/cc-HelpRequest-backend","number":68,"title":"Add HelpRequest backend CRUD API","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/68"},{"author":{"id":"U_kgDODgRftg","is_bot":false,"login":"CMWENDY","name":"Wendy Contreras"},"headRefName":"wc-UCSBDiningCommonsMenuItem-fixtures","number":67,"title":"Copy UCSBDiningCommonsMenuItem backend CRUD API from team01","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/67"},{"author":{"id":"U_kgDODgRftg","is_bot":false,"login":"CMWENDY","name":"Wendy Contreras"},"headRefName":"wc-UCSBDiningCommonsMenuItem-backend","number":66,"title":"Copy UCSBDiningCommonsMenuItem backend CRUD API from team01","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/66"},{"author":{"id":"U_kgDOB-HICA","is_bot":false,"login":"taedonreth","name":"Taedon Reth"},"headRefName":"tr-migrate-article-files","number":65,"title":"Migrate backend files for Articles from team01","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/65"},{"author":{"id":"U_kgDOCVHlaQ","is_bot":false,"login":"riasingh455","name":""},"headRefName":"rs-recommendation-fixtures","number":64,"title":"redo the fixtures branch","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/64"},{"author":{"id":"U_kgDOCVPcVQ","is_bot":false,"login":"matthewli10","name":""},"headRefName":"matthewli-copy-files","number":62,"title":"ML - copy UCSBOrganization files from team01","url":"https://github.com/ucsb-cs156-s26/team02-s26-08/pull/62"}]
